import '../models/brand.dart';
import '../models/category.dart';
import '../models/customer.dart';
import '../models/product.dart';
import '../models/supplier.dart';

const seedCategories = <Category>[
  Category(id: 1, name: 'Смартфоны', description: 'Мобильные телефоны'),
  Category(id: 2, name: 'Ноутбуки', description: 'Портативные ПК'),
  Category(id: 3, name: 'Планшеты', description: 'Планшетные компьютеры'),
  Category(id: 4, name: 'Наушники', description: 'Аудиоаксессуары'),
  Category(id: 5, name: 'Телевизоры', description: 'ТВ и панели'),
  Category(id: 6, name: 'Игровые приставки', description: 'Консоли'),
  Category(id: 7, name: 'Бытовая техника', description: 'Дом и кухня'),
  Category(id: 8, name: 'Фототехника', description: 'Камеры'),
  Category(id: 9, name: 'Оргтехника', description: 'Принтеры и МФУ'),
];

const seedSuppliers = <Supplier>[
  Supplier(
    id: 1,
    name: 'Дистрибьютор Центр',
    country: 'Россия',
    phone: '+7-495-100-00-01',
  ),
  Supplier(
    id: 2,
    name: 'EuroTech Supply',
    country: 'Германия',
    phone: '+49-30-200-00-02',
  ),
  Supplier(
    id: 3,
    name: 'Asia Gadgets Ltd',
    country: 'Китай',
    phone: '+86-10-300-00-03',
  ),
];

const seedBrands = <Brand>[
  Brand(
    id: 1,
    name: 'Apple',
    foundedYear: 1976,
    country: 'США',
    email: 'support@apple.com',
  ),
  Brand(
    id: 2,
    name: 'Samsung',
    foundedYear: 1938,
    country: 'Южная Корея',
    email: 'support@samsung.com',
  ),
  Brand(
    id: 3,
    name: 'Sony',
    foundedYear: 1946,
    country: 'Япония',
    email: 'support@sony.com',
  ),
  Brand(
    id: 4,
    name: 'LG',
    foundedYear: 1958,
    country: 'Южная Корея',
    email: 'support@lg.com',
  ),
  Brand(
    id: 5,
    name: 'Xiaomi',
    foundedYear: 2010,
    country: 'Китай',
    email: 'support@xiaomi.com',
  ),
  Brand(
    id: 6,
    name: 'ASUS',
    foundedYear: 1989,
    country: 'Тайвань',
    email: 'support@asus.com',
  ),
  Brand(
    id: 7,
    name: 'Bosch',
    foundedYear: 1886,
    country: 'Германия',
    email: 'support@bosch.com',
  ),
  Brand(
    id: 8,
    name: 'Canon',
    foundedYear: 1937,
    country: 'Япония',
    email: 'support@canon.com',
  ),
  Brand(
    id: 9,
    name: 'Dyson',
    foundedYear: 1991,
    country: 'Великобритания',
    email: 'support@dyson.com',
  ),
  Brand(
    id: 10,
    name: 'Nintendo',
    foundedYear: 1889,
    country: 'Япония',
    email: 'support@nintendo.com',
  ),
];

const seedCustomers = <Customer>[
  Customer(
    id: 1,
    fullName: 'Иван Петров',
    email: 'ivan.petrov@mail.ru',
    phone: '+7-900-111-22-33',
    card: MembershipCard(
      number: 'TM-CARD-001',
      level: 'Gold',
      issuedYear: 2023,
    ),
  ),
  Customer(
    id: 2,
    fullName: 'Мария Сидорова',
    email: 'maria.sidorova@mail.ru',
    phone: '+7-900-222-33-44',
    card: MembershipCard(
      number: 'TM-CARD-002',
      level: 'Standard',
      issuedYear: 2024,
    ),
  ),
  Customer(
    id: 3,
    fullName: 'Алексей Козлов',
    email: 'alex.kozlov@mail.ru',
    phone: '+7-900-333-44-55',
    card: MembershipCard(
      number: 'TM-CARD-003',
      level: 'Platinum',
      issuedYear: 2022,
    ),
  ),
];

const supplierBrandIds = <int, List<int>>{
  1: [1, 6, 8], // Центр далее Apple, ASUS, Canon
  2: [2, 4, 7, 9], // EuroTech \далее Samsung, LG, Bosch, Dyson
  3: [3, 5, 10], // Asia далее Sony, Xiaomi, Nintendo
};

const supplierCategoryIds = <int, List<int>>{
  1: [1, 2, 3, 4, 8, 9],
  2: [1, 2, 4, 5, 7],
  3: [1, 4, 5, 6, 7],
};

const seedProducts = <Product>[
  Product(
    id: 1,
    name: 'iPhone 15 Pro',
    sku: 'TM-000001',
    year: 2023,
    price: 129990,
    supplierId: 1,
    brandIds: [1],
    categoryIds: [1],
    stockTotal: 20,
    stockAvailable: 14,
  ),
  Product(
    id: 2,
    name: 'MacBook Air 13 M3',
    sku: 'TM-000002',
    year: 2024,
    price: 149990,
    supplierId: 1,
    brandIds: [1],
    categoryIds: [2],
    stockTotal: 12,
    stockAvailable: 8,
  ),
  Product(
    id: 3,
    name: 'iPad Pro 11',
    sku: 'TM-000003',
    year: 2024,
    price: 119990,
    supplierId: 1,
    brandIds: [1],
    categoryIds: [3],
    stockTotal: 10,
    stockAvailable: 6,
  ),
  Product(
    id: 4,
    name: 'AirPods Pro 2',
    sku: 'TM-000004',
    year: 2023,
    price: 24990,
    supplierId: 1,
    brandIds: [1],
    categoryIds: [4],
    stockTotal: 30,
    stockAvailable: 22,
  ),
  Product(
    id: 5,
    name: 'Galaxy S24 Ultra',
    sku: 'TM-000005',
    year: 2024,
    price: 119990,
    supplierId: 2,
    brandIds: [2],
    categoryIds: [1],
    stockTotal: 18,
    stockAvailable: 11,
  ),
  Product(
    id: 6,
    name: 'Samsung QE55Q80D',
    sku: 'TM-000006',
    year: 2024,
    price: 99990,
    supplierId: 2,
    brandIds: [2],
    categoryIds: [5],
    stockTotal: 8,
    stockAvailable: 5,
  ),
  Product(
    id: 7,
    name: 'Galaxy Buds 3 Pro',
    sku: 'TM-000007',
    year: 2024,
    price: 19990,
    supplierId: 2,
    brandIds: [2],
    categoryIds: [4],
    stockTotal: 25,
    stockAvailable: 19,
  ),
  Product(
    id: 8,
    name: 'PlayStation 5 Slim',
    sku: 'TM-000008',
    year: 2023,
    price: 54990,
    supplierId: 3,
    brandIds: [3],
    categoryIds: [6],
    stockTotal: 15,
    stockAvailable: 4,
  ),
  Product(
    id: 9,
    name: 'WH-1000XM5',
    sku: 'TM-000009',
    year: 2022,
    price: 34990,
    supplierId: 3,
    brandIds: [3],
    categoryIds: [4],
    stockTotal: 16,
    stockAvailable: 9,
  ),
  Product(
    id: 10,
    name: 'Sony Bravia XR-55A80L',
    sku: 'TM-000010',
    year: 2023,
    price: 139990,
    supplierId: 3,
    brandIds: [3],
    categoryIds: [5],
    stockTotal: 6,
    stockAvailable: 3,
  ),
  Product(
    id: 11,
    name: 'LG OLED55C3',
    sku: 'TM-000011',
    year: 2023,
    price: 129990,
    supplierId: 2,
    brandIds: [4],
    categoryIds: [5],
    stockTotal: 7,
    stockAvailable: 2,
  ),
  Product(
    id: 12,
    name: 'LG gram 16',
    sku: 'TM-000012',
    year: 2024,
    price: 139990,
    supplierId: 2,
    brandIds: [4],
    categoryIds: [2],
    stockTotal: 9,
    stockAvailable: 7,
  ),
  Product(
    id: 13,
    name: 'Redmi Note 13 Pro',
    sku: 'TM-000013',
    year: 2024,
    price: 32990,
    supplierId: 3,
    brandIds: [5],
    categoryIds: [1],
    stockTotal: 40,
    stockAvailable: 28,
  ),
  Product(
    id: 14,
    name: 'Xiaomi Robot Vacuum S10',
    sku: 'TM-000014',
    year: 2023,
    price: 27990,
    supplierId: 3,
    brandIds: [5],
    categoryIds: [7],
    stockTotal: 14,
    stockAvailable: 10,
  ),
  Product(
    id: 15,
    name: 'ASUS ROG Zephyrus G16',
    sku: 'TM-000015',
    year: 2024,
    price: 189990,
    supplierId: 1,
    brandIds: [6],
    categoryIds: [2],
    stockTotal: 5,
    stockAvailable: 2,
  ),
  Product(
    id: 16,
    name: 'ASUS TUF Gaming A15',
    sku: 'TM-000016',
    year: 2023,
    price: 99990,
    supplierId: 1,
    brandIds: [6],
    categoryIds: [2],
    stockTotal: 11,
    stockAvailable: 6,
  ),
  Product(
    id: 17,
    name: 'Bosch Serie 8 SMS8ZCI48Q',
    sku: 'TM-000017',
    year: 2023,
    price: 89990,
    supplierId: 2,
    brandIds: [7],
    categoryIds: [7],
    stockTotal: 8,
    stockAvailable: 5,
  ),
  Product(
    id: 18,
    name: 'Bosch KGN39VI306',
    sku: 'TM-000018',
    year: 2022,
    price: 79990,
    supplierId: 2,
    brandIds: [7],
    categoryIds: [7],
    stockTotal: 6,
    stockAvailable: 4,
  ),
  Product(
    id: 19,
    name: 'Canon EOS R8',
    sku: 'TM-000019',
    year: 2023,
    price: 159990,
    supplierId: 1,
    brandIds: [8],
    categoryIds: [8],
    stockTotal: 7,
    stockAvailable: 3,
  ),
  Product(
    id: 20,
    name: 'Canon PIXMA G3470',
    sku: 'TM-000020',
    year: 2023,
    price: 24990,
    supplierId: 1,
    brandIds: [8],
    categoryIds: [9],
    stockTotal: 13,
    stockAvailable: 9,
  ),
  Product(
    id: 21,
    name: 'Dyson V15 Detect',
    sku: 'TM-000021',
    year: 2023,
    price: 69990,
    supplierId: 2,
    brandIds: [9],
    categoryIds: [7],
    stockTotal: 10,
    stockAvailable: 6,
  ),
  Product(
    id: 22,
    name: 'Nintendo Switch OLED',
    sku: 'TM-000022',
    year: 2021,
    price: 34990,
    supplierId: 3,
    brandIds: [10],
    categoryIds: [6],
    stockTotal: 20,
    stockAvailable: 12,
  ),
];
